
server:
  port: 9998
file:
  path: ${file.path}
  host: ${file.host}
  port: ${server.port}
spring:
  profiles:
    include:
      - local
  devtools:
    restart:
      enabled: true
      exclude: static/**
    livereload:
      enabled: true
  application:
    name: file-server
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 10GB
logging:
  level:
    '[org.river.file_server.controller]': debug

